import type { KnowledgeChunk } from "./profile";

// ----------------------------------------------------------------------------
//  KNOWLEDGE BASE  — the retrievable units the chat answers from.
//  All written in first person ("I / me / my").
//
//  ROLE-AWARE: chunks are written so the chat can tailor answers to
//  whichever role family a recruiter asks about. The "role-fit-*" chunks
//  explicitly map experience → role type.
// ----------------------------------------------------------------------------

export const knowledgeChunks: KnowledgeChunk[] = [
  // ---- Identity & overview ----
  {
    id: "intro",
    title: "Who I am",
    source: "Profile",
    keywords: [
      "who",
      "baavansh",
      "about",
      "summary",
      "introduce",
      "yourself",
      "background",
      "overview",
      "person",
      "tell",
    ],
    text: "I'm Baavansh Reddy Gundlapalli, a backend and AI systems engineer with four years of engineering experience across REST APIs and IoT platforms, and now LLM and ML integration in backend services. My core stack is Python, Java, and C, and my work runs from authentication systems and data pipelines down to compilers, CPU simulators, and operating systems. I graduated from Rutgers University with a B.S. in Computer Science, Magna Cum Laude, 3.76 GPA, and I'm currently a Backend & AI Systems Engineer at TAIRC.",
  },
  {
    id: "experience-span",
    title: "How much experience I have",
    source: "Profile",
    keywords: [
      "experience",
      "years",
      "how",
      "long",
      "many",
      "four",
      "4",
      "senior",
      "junior",
      "level",
      "entry",
      "early",
      "career",
      "timeline",
      "history",
    ],
    text: "I have four years of engineering experience, starting in August 2022. It runs continuously: a Java and Spring Boot business-systems internship at RNR (2022–2023), two years at KAVACH/VIANSEC Solutions on an IoT security platform (first as a software engineering intern, then as a backend and IoT engineering intern, 2023–2025), a software engineering externship with Little Red Riding Hood Inc. (2025), a full-stack externship at LIVELY (2026), and now backend and AI systems engineering at TAIRC. That's production work alongside my degree, not a gap-filled timeline.",
  },
  {
    id: "approach",
    title: "How I work",
    source: "About",
    keywords: [
      "adaptable",
      "resourceful",
      "charge",
      "leadership",
      "approach",
      "different",
      "strength",
      "stand",
      "out",
      "team",
      "initiative",
      "ownership",
      "special",
      "unique",
      "style",
    ],
    text: "What sets me apart is ownership. I like taking a problem end to end: mapping it, weighing two or three approaches, then shipping a solution rather than handing it off. I also have unusual range: I'm comfortable from database and backend APIs up to the UI, from IoT device telemetry up to an LLM retrieval pipeline, and down to the compiler and OS internals I studied. That range means I can debug across the full stack and understand how the pieces fit together.",
  },

  // ---- ROLE-FIT CHUNKS — the smart part ----
  {
    id: "role-fit-backend",
    title: "Why I'm a fit for backend roles",
    source: "Role Fit",
    keywords: [
      "backend",
      "back-end",
      "server",
      "api",
      "apis",
      "microservices",
      "services",
      "infrastructure",
      "distributed",
      "scalable",
      "rest",
      "endpoint",
      "database",
      "sql",
      "schema",
    ],
    text: "For backend roles: I build and maintain Python backend services and REST APIs at TAIRC today, designing relational schemas and data-access layers and converting research prototypes into deployable, tested endpoints. Before that I engineered secure role-based authentication, credential management, session tracking, and real-time geolocation on AWS-deployed services at Little Red Riding Hood Inc.; REST API routes plus a Supabase/PostgreSQL backend for the LIVEY event platform; and a Java/Spring Boot work-order application on MySQL at RNR. I've worked with PostgreSQL, MySQL, SQLite, Supabase, Express, FastAPI, and Docker. My systems background (compilers, OS, computer architecture) means I reason about performance and memory, not just the API surface.",
  },
  {
    id: "role-fit-aiml",
    title: "Why I'm a fit for AI/ML roles",
    source: "Role Fit",
    keywords: [
      "ai",
      "ml",
      "machine",
      "learning",
      "artificial",
      "intelligence",
      "ai/ml",
      "aiml",
      "data",
      "scientist",
      "nlp",
      "deep",
      "model",
      "training",
      "inference",
      "llm",
      "genai",
    ],
    text: "For AI/ML roles: at TAIRC I integrate LLM and machine-learning components into backend services: model invocation, prompt orchestration, retrieval, and output evaluation. On my own I built and published AgentMemry, an open-source Python library on PyPI for persistent agent memory (local embeddings, cosine similarity, MMR). As personal projects I built an MLOps deployment lab (Feast, MLflow registry with promotion and rollback, FastAPI micro-batching, Prometheus and Evidently monitoring), a Responsible AI evaluation system (SHAP, Fairlearn), and a neural network training benchmark in NumPy, PyTorch, and TensorFlow/Keras. I also co-authored LLM FactCheck, a study of direct prompting vs BM25 vs RAG. To be precise: the ML platform work is project experience measured locally on CPU, not production ML at an employer.",
  },
  {
    id: "role-fit-python",
    title: "Why I'm a fit for Python roles",
    source: "Role Fit",
    keywords: [
      "python",
      "developer",
      "scripting",
      "automation",
      "script",
      "programming",
      "django",
      "flask",
      "fastapi",
      "pandas",
    ],
    text: "For Python roles: Python is my primary language and runs through almost everything I've built. My backend services and REST APIs at TAIRC are Python. AgentMemry is a pure Python library (~500 lines, 15 pytest tests, published on PyPI). My TinyL compiler is Python. My neural network is Python + NumPy. My campus event scraper is Python + BeautifulSoup + SQLite. I use FastAPI for backend services and pytest for verification. I think in Python; it's where I'm fastest.",
  },
  {
    id: "role-fit-iot",
    title: "Why I'm a fit for IoT / connected-systems roles",
    source: "Role Fit",
    keywords: [
      "iot",
      "internet",
      "of",
      "things",
      "connected",
      "device",
      "devices",
      "embedded",
      "edge",
      "firmware",
      "sensor",
      "sensors",
      "telemetry",
      "azure",
      "google",
      "gcp",
      "aws",
      "cloud",
      "platform",
      "platforms",
      "level",
      "3",
      "production",
      "support",
      "scale",
      "performance",
      "hardware",
      "kavach",
      "viansec",
    ],
    text: "For IoT and connected-systems roles: I spent two years at KAVACH (VIANSEC Solutions) on a real IoT security platform. As a backend and IoT engineering intern I integrated IoT telemetry and AI-generated detections into incident and alert workflows, validated device-data flows, monitored system behavior, documented integration issues, and supported troubleshooting. Before that I built dashboard functionality for user access, site operations, incident tracking, and alert management, and supported Docker-based deployments. Underneath that I have the systems foundation IoT sits on: a single-cycle RISC-V CPU and a Unix-style filesystem written in C, plus computer architecture and operating systems coursework, and the cloud side: AWS-deployed services, Docker, and S3-compatible object storage. Device data at one end, cloud services at the other; I've worked at both.",
  },
  {
    id: "role-fit-it",
    title: "Why I'm a fit for IT / infrastructure roles",
    source: "Role Fit",
    keywords: [
      "it",
      "information",
      "technology",
      "support",
      "helpdesk",
      "help",
      "desk",
      "sysadmin",
      "admin",
      "administrator",
      "network",
      "troubleshoot",
      "troubleshooting",
      "infrastructure",
      "security",
      "devops",
      "operations",
      "deploy",
      "deployment",
      "docker",
    ],
    text: "For IT and infrastructure roles: I've supported Docker-based deployments and application debugging at KAVACH, worked hands-on with AWS-deployed services (session tracking and geolocation handling), administered PostgreSQL and MySQL databases, built authentication and credential-management systems, and run Git-based deployment workflows on Vercel and GitHub. At KAVACH I also monitored system behavior, validated data flows, and documented integration issues, which is day-to-day operational troubleshooting. My operating systems and computer architecture coursework gives me a real foundation for system internals and debugging, and as a Community Service Officer with Rutgers University Police I developed incident response and coordination skills that translate directly to operations work.",
  },
  {
    id: "role-fit-java",
    title: "Java and Spring Boot experience",
    source: "Role Fit",
    keywords: [
      "java",
      "spring",
      "boot",
      "springboot",
      "jvm",
      "enterprise",
      "mysql",
      "rnr",
      "backend",
      "oop",
    ],
    text: "On the Java side: at RNR Facilities (now RNR Infra) I contributed to a Java and Spring Boot work-order and vendor-tracking application backed by MySQL, and tested and documented application features while maintaining database records and operational reports. I also built RuPizza, a JavaFX desktop ordering application designed around inheritance, polymorphism, and the Factory pattern with JUnit test coverage. Java is one of my three core languages alongside Python and C.",
  },

  // ---- Projects ----
  {
    id: "agentmemry",
    title: "AgentMemry: open-source memory for AI agents, on PyPI",
    source: "Projects · AgentMemry",
    keywords: [
      "agentmemry",
      "agentmem",
      "memory",
      "agent",
      "agents",
      "library",
      "open",
      "source",
      "sqlite",
      "embeddings",
      "package",
      "pypi",
      "pip",
      "published",
      "main",
      "best",
      "flagship",
      "top",
      "project",
    ],
    text: "AgentMemry is my flagship project: a ~500-line open-source Python library, published on PyPI, that gives AI agents persistent memory without a cloud database or any API keys. It stores memories in a single SQLite file, embeds them locally with sentence-transformers, and retrieves them by cosine similarity. It also has an MMR diversity mode and per-agent namespacing so multiple agents can share one database safely. The public API is covered by 15 pytest tests. Install it with `pip install agentmemry`; source at github.com/BaavanshReddy/agentmemry, package at pypi.org/project/agentmemry.",
  },
  {
    id: "tinyl",
    title: "TinyL Compiler",
    source: "Projects",
    keywords: [
      "tinyl",
      "compiler",
      "compilers",
      "lexer",
      "parser",
      "parsing",
      "codegen",
      "ast",
      "language",
      "grammar",
    ],
    text: "My TinyL compiler is a full pipeline: I wrote the lexer, a recursive-descent parser working from a formal grammar, AST construction, an intermediate representation, and a code generator targeting stack-based bytecode. Source: github.com/BaavanshReddy/tinyl-compiler.",
  },
  {
    id: "neuralnet",
    title: "Neural Network from Scratch",
    source: "Projects",
    keywords: [
      "neural",
      "net",
      "network",
      "perceptron",
      "backprop",
      "backpropagation",
      "numpy",
      "pytorch",
      "ml",
      "deep",
      "learning",
      "scratch",
    ],
    text: "I implemented a perceptron and a 3-layer neural network from scratch with hand-coded forward propagation and backpropagation in NumPy. My training benchmark later rebuilt it in PyTorch and Keras on the same data, weights, and batch order: in float64 all three agree to within 1e-15, and they reach 90.2% digit and 90.9% face test accuracy over 3 seeds. (An older results file in the repo shows 86.7% and 89.1%, but the script that produced it is not in the repository, so I quote the reproducible numbers.)",
  },
  {
    id: "rupizza",
    title: "RuPizza: OOP Ordering App",
    source: "Projects",
    keywords: [
      "rupizza",
      "pizza",
      "javafx",
      "junit",
      "oop",
      "object",
      "oriented",
      "factory",
      "pattern",
      "design",
    ],
    text: "RuPizza is a JavaFX desktop ordering application I built around object-oriented principles (inheritance, polymorphism, and the Factory pattern), featuring an order builder, store-order management, and JUnit test coverage.",
  },
  {
    id: "scraper",
    title: "Campus Event Scraper",
    source: "Projects",
    keywords: [
      "scraper",
      "scrape",
      "scraping",
      "beautifulsoup",
      "events",
      "sqlite",
      "pipeline",
      "backoff",
      "retry",
      "automation",
    ],
    text: "I built a Python web-scraping pipeline that collects and normalizes university event listings into an indexed SQLite database. It stays reliable through exponential-backoff retries, URL-based deduplication, and graceful offline fallback when sources are unavailable.",
  },
  {
    id: "systems-projects",
    title: "Systems projects in C: RISC-V CPU and Unix filesystem",
    source: "Projects · Systems",
    keywords: [
      "risc-v",
      "riscv",
      "cpu",
      "simulator",
      "processor",
      "datapath",
      "filesystem",
      "file",
      "system",
      "inode",
      "unix",
      "linux",
      "c",
      "low-level",
      "kernel",
      "os",
    ],
    text: "Beyond the compiler, I've written a single-cycle RISC-V RV32I CPU simulator in C (instruction decode, datapath, register file, and a 1 KiB direct-mapped cache; github.com/BaavanshReddy/risc-v-simulator) and a Linux-like virtual filesystem in C with inode architecture, Unix permissions, persistent serialization, and an interactive shell (github.com/BaavanshReddy/linux-filesystem). These are the projects that taught me how code actually executes on hardware: memory hierarchies, instruction cycles, and what an operating system is really doing underneath a system call.",
  },

  // ---- Experience ----
  {
    id: "tairc",
    title: "TAIRC: current role",
    source: "TAIRC · Experience",
    keywords: [
      "tairc",
      "research",
      "center",
      "current",
      "currently",
      "now",
      "present",
      "today",
      "engineer",
      "job",
      "work",
      "role",
      "experience",
      "where",
    ],
    text: "I'm currently a Backend & AI Systems Engineer at TAIRC (The AI Research Center), since June 2026. I build and maintain Python backend services and REST APIs, designing relational schemas and data-access layers that support AI-enabled research and production applications. I integrate LLM and machine-learning components into those services (model invocation, prompt orchestration, retrieval, and output evaluation) and convert research prototypes into deployable, tested endpoints, owning features from requirements analysis through API design, implementation, testing, and deployment.",
  },
  {
    id: "kavach",
    title: "KAVACH (VIANSEC Solutions): two years on an IoT platform",
    source: "KAVACH · Experience",
    keywords: [
      "kavach",
      "viansec",
      "iot",
      "telemetry",
      "device",
      "detection",
      "detections",
      "alert",
      "alerts",
      "incident",
      "dashboard",
      "hyderabad",
      "india",
      "internship",
      "intern",
      "security",
      "docker",
      "testing",
    ],
    text: "I spent two years at KAVACH (VIANSEC Solutions Pvt. Ltd.) in Hyderabad, India. As Backend & IoT Engineering Intern (Aug 2024 – Aug 2025) I collaborated with the engineering team to integrate IoT telemetry and AI-generated detections into incident and alert workflows, validated device-data flows, monitored system behavior, documented integration issues, and supported troubleshooting. Before that, as Software Engineering Intern (Sep 2023 – Aug 2024), I contributed to dashboard functionality for user access, site operations, incident tracking, and alert management, performed software testing, documented defects, and supported Docker-based deployments and application debugging.",
  },
  {
    id: "rnr",
    title: "RNR Facilities: Java and Spring Boot business systems",
    source: "RNR · Experience",
    keywords: [
      "rnr",
      "facilities",
      "infra",
      "java",
      "spring",
      "boot",
      "mysql",
      "work",
      "order",
      "vendor",
      "tracking",
      "business",
      "first",
      "earliest",
      "2022",
    ],
    text: "My first engineering role was at RNR Facilities Pvt. Ltd. (now RNR Infra Pvt. Ltd.) in Hyderabad, India, from Aug 2022 to Aug 2023, as a Software & Business Systems Intern. I contributed to development of a Java and Spring Boot work-order and vendor-tracking application backed by MySQL, and tested and documented application features while maintaining database records and operational reports.",
  },
  {
    id: "lively",
    title: "LIVELY: full-stack event platform",
    source: "Experience",
    keywords: [
      "livey",
      "lively",
      "jillcyn",
      "event",
      "fullstack",
      "full-stack",
      "react",
      "supabase",
      "postgres",
      "frontend",
      "extern",
      "externship",
      "mbs",
    ],
    text: "As a full-stack engineering extern at LIVELY (Jillcyn Enterprises, LLC) through the Rutgers MBS Externship Exchange from Jan to May 2026, I co-built LIVEY, a full-stack event-discovery platform. I developed React search and filtering components, engineered REST API routes across the front and back end, and integrated Supabase (PostgreSQL) for real-time data storage, user authentication, and event management.",
  },
  {
    id: "rideshare",
    title: "Rideshare backend: Little Red Riding Hood Inc.",
    source: "Experience",
    keywords: [
      "rideshare",
      "ride",
      "little",
      "red",
      "riding",
      "hood",
      "auth",
      "authentication",
      "login",
      "geolocation",
      "extern",
      "aws",
      "security",
      "session",
      "safety",
    ],
    text: "As a software engineering extern with Little Red Riding Hood Inc. (Rutgers MBS Externship Exchange, Sep – Dec 2025), I built backend systems for a safety-focused rideshare platform. I engineered secure authentication with role-based login and credential management for separate rider and driver accounts, and built driver session tracking and real-time geolocation handling on cloud-deployed (AWS) services, supporting dispatch coordination and passenger-safety workflows.",
  },

  // ---- Skills & depth ----
  {
    id: "systems",
    title: "Systems & compilers background",
    source: "Projects · Systems",
    keywords: [
      "systems",
      "compiler",
      "compilers",
      "architecture",
      "operating",
      "low-level",
      "depth",
      "technical",
      "os",
      "cpu",
      "memory",
    ],
    text: "I have a deeper systems background than most candidates at my stage. I built a full compiler for the TinyL language (lexer, recursive-descent parser, AST, intermediate representation, and code generation), a single-cycle RISC-V CPU simulator in C, and a Unix-style filesystem with inodes and persistence, alongside coursework in computer architecture and operating systems. Being able to reason about parsers, datapaths, memory management, and how code actually runs is an edge whether I'm building an AI pipeline, debugging a backend service, or tracing an IoT device-data flow.",
  },
  {
    id: "backend-skills",
    title: "Backend & engineering skills",
    source: "Skills · Experience",
    keywords: [
      "node",
      "nodejs",
      "typescript",
      "express",
      "fastapi",
      "api",
      "rest",
      "engineering",
      "build",
      "ship",
      "code",
      "stack",
      "tech",
    ],
    text: "My backend stack is Python (FastAPI), Java (Spring Boot), Node.js and Express, on PostgreSQL, MySQL, SQLite, and Supabase, deployed with Docker, AWS, and Vercel. I've built REST APIs and relational schemas at TAIRC, secure role-based auth and real-time geolocation at Little Red Riding Hood Inc., REST routes and a Supabase backend for LIVEY, and a Spring Boot work-order system on MySQL at RNR. I verify with pytest and JUnit and work in Agile teams.",
  },
  {
    id: "ai-skills",
    title: "AI & retrieval skills",
    source: "Skills",
    keywords: [
      "skills",
      "rag",
      "vector",
      "embeddings",
      "llm",
      "claude",
      "prompt",
      "eval",
      "evaluation",
      "retrieval",
      "semantic",
      "search",
      "sentence-transformers",
    ],
    text: "My AI work centers on retrieval, memory, evaluation, and ML systems: LLM integration, retrieval pipelines, embeddings and hand-rolled cosine-similarity search (no vector database), prompt engineering, and LLM evaluation, plus model training and serving with PyTorch, TensorFlow/Keras, scikit-learn, ONNX Runtime, MLflow, Feast, SHAP, Fairlearn, and Evidently. At TAIRC I integrate LLM components into backend services. On my own time I built and published AgentMemry, wrote this site's knowledge-base assistant, and co-authored a study evaluating LLM factual question answering. Separately, as personal projects, I built three ML systems: an MLOps lab, a Responsible AI evaluation, and a training benchmark.",
  },
  {
    id: "python-skills",
    title: "Python expertise",
    source: "Skills",
    keywords: [
      "python",
      "language",
      "primary",
      "comfortable",
      "strongest",
      "proficient",
      "fluent",
    ],
    text: "Python is my primary language. It's what I reach for first and where I'm most productive. I've used it for: production backend services and REST APIs (TAIRC), an open-source library with a pytest suite (AgentMemry, on PyPI), compilers (TinyL), neural networks (NumPy + PyTorch), web scraping and data pipelines (BeautifulSoup + SQLite), backend APIs (FastAPI), and research (LLM FactCheck).",
  },

  // ---- ML systems (personal projects; see lib/caseStudies.ts) ----
  {
    id: "ml-systems-overview",
    title: "My ML systems experience",
    source: "ML Systems",
    keywords: [
      "ml",
      "systems",
      "mlops",
      "machine",
      "learning",
      "engineer",
      "experience",
      "platform",
      "pipeline",
      "models",
      "deploy",
      "deployment",
      "lifecycle",
      "production",
      "built",
    ],
    text: "My ML systems work is three personal projects, each built and measured locally on one CPU machine: an MLOps Deployment Lab (data contracts, a Feast feature store, scikit-learn and PyTorch models in an MLflow registry with a promotion policy and rollback, FastAPI serving with micro-batching, Prometheus and Evidently monitoring), a Responsible AI Evaluation System (SHAP, Fairlearn subgroup diagnostics, model cards, release evidence), and a Neural Network Training Benchmark (NumPy, PyTorch, and Keras parity, DDP, ONNX Runtime). Professionally, I integrate LLM and ML components into backend services at TAIRC. Case studies with every measured number are at /projects on this site.",
  },
  {
    id: "project-vs-production",
    title: "Project experience vs professional production experience",
    source: "ML Systems · Boundaries",
    keywords: [
      "production",
      "professional",
      "employer",
      "shipped",
      "shipping",
      "years",
      "five",
      "5",
      "two",
      "2",
      "senior",
      "enterprise",
      "real",
      "users",
      "difference",
      "tairc",
    ],
    text: "I keep a clear line here. My professional experience is about four years of internships, externships, and my current TAIRC role, mostly backend, IoT, and LLM/ML integration work; it is not five or more years, and I have not spent two or more years shipping production ML models. My MLOps lab, Responsible AI evaluation, and training benchmark are personal projects: built, tested, and measured locally, never deployed to production, never serving real users, and not done for TAIRC or any other employer. I describe them as project experience.",
  },
  {
    id: "mlops-lab-architecture",
    title: "MLOps Deployment Lab architecture",
    source: "ML Systems · MLOps Lab",
    keywords: [
      "mlops",
      "lab",
      "deployment",
      "architecture",
      "design",
      "pipeline",
      "uci",
      "adult",
      "census",
      "income",
      "contract",
      "contracts",
      "ingestion",
      "leakage",
      "endpoints",
      "api",
      "components",
    ],
    text: "The MLOps Deployment Lab is a local end-to-end platform on the UCI Adult census dataset (48,842 rows, 52 duplicates removed). Ingestion checks a SHA-256-pinned file against a YAML data contract, which also generates the API request schema, and runs target and split leakage checks. One shared feature transform feeds Feast; training reads point-in-time features, logs to MLflow, and registers versions; a promotion policy moves the @champion alias; FastAPI serves /v1/predict (micro-batched), /v1/predict/batch, and /v1/predict/entity; Prometheus and Evidently watch it. It is a personal project, not work for TAIRC or any other employer, and it is educational: the model must not be used on real people.",
  },
  {
    id: "mlflow-feast",
    title: "MLflow and Feast in my lab",
    source: "ML Systems · MLOps Lab",
    keywords: [
      "mlflow",
      "feast",
      "feature",
      "store",
      "registry",
      "tracking",
      "experiment",
      "aliases",
      "alias",
      "champion",
      "promotion",
      "policy",
      "versioning",
      "parity",
      "skew",
      "online",
      "offline",
    ],
    text: "Feast holds the lab's features: a file offline store for point-in-time training data and a SQLite online store for serving. A parity test compares Feast offline, Feast online, and request-time features and model probabilities on 500 rows and requires a max difference of 0.0. MLflow tracks every run (params, metrics, plots, environment, Git commit, config hash, dataset inputs) and registers versions. Promotion is policy as config: validation ROC AUC of at least 0.85, Brier score of at most 0.15, ONNX fidelity within 1e-4, passed contract and parity tags, and no regression against the champion. v1 (scikit-learn, val AUC 0.901) and then v2 (PyTorch via ONNX, val AUC 0.909) were promoted on the Docker Compose stack.",
  },
  {
    id: "online-offline-inference",
    title: "Online and offline inference",
    source: "ML Systems · MLOps Lab",
    keywords: [
      "inference",
      "online",
      "offline",
      "batch",
      "serving",
      "fastapi",
      "micro-batching",
      "microbatching",
      "batching",
      "latency",
      "throughput",
      "requests",
      "locust",
      "load",
      "api",
    ],
    text: "Online, my lab's FastAPI service validates each record against the data contract and an async micro-batcher groups concurrent requests so the model runs once per group. In local Locust tests on a 1-CPU container, batching gave 146 vs 75 requests per second at 64 users (1.95x) and 133 vs 75 at 16 users, with 0 errors; it costs about 6 ms at 1 user. There is also a batch endpoint (up to 1,000 records) and an entity endpoint that reads the Feast online store. Offline, a batch CLI scored the 7,319-row test split, and a test asserts its probabilities match the online API to within 1e-12. These are relative numbers from a small VM, not capacity figures.",
  },
  {
    id: "docker-kubernetes",
    title: "Docker and local Kubernetes",
    source: "ML Systems · MLOps Lab",
    keywords: [
      "docker",
      "compose",
      "kubernetes",
      "k8s",
      "kind",
      "container",
      "containers",
      "helm",
      "blue-green",
      "bluegreen",
      "hpa",
      "pods",
      "cluster",
      "enterprise",
      "orchestration",
    ],
    text: "In the lab, Docker Compose runs MLflow, the API, and Prometheus, and the serving image is multi-stage and non-root with a read-only filesystem. For Kubernetes I wrote blue-green manifests with probes, resource limits, an HPAs, and PodDisruptionBudgets; all 11 resources pass kubeconform and a server-side dry run on a real Kubernetes 1.31 API server, and I exercised the blue-green selector switch there. No pod actually ran in that sandbox, so I have not observed autoscaling or live traffic switching. That is local manifest work, not enterprise or production Kubernetes experience. Professionally, I supported Docker-based deployments at KAVACH.",
  },
  {
    id: "monitoring-drift",
    title: "Monitoring and drift detection",
    source: "ML Systems · MLOps Lab",
    keywords: [
      "monitoring",
      "drift",
      "prometheus",
      "evidently",
      "alert",
      "alerts",
      "observability",
      "metrics",
      "grafana",
      "data",
      "quality",
      "shift",
      "detection",
      "dashboard",
    ],
    text: "The lab exports Prometheus metrics (latency, errors, batch size, model version, prediction distribution, and a rolling positive rate compared with the model's own validation baseline) and has five alert rules. Evidently produces data quality, input drift, prediction drift, and performance reports for a baseline and a documented synthetic shift: the baseline stays quiet, and the shifted data raised an alert with prediction drift of 0.362. Replaying shifted traffic through the live API pushed the positive rate to 0.444 against an expected 0.325 and fired the PredictionPositiveRateShift alert. The Grafana dashboard's 17 queries were verified against Prometheus, but Grafana itself was never rendered.",
  },
  {
    id: "model-rollback",
    title: "Model rollback",
    source: "ML Systems · MLOps Lab",
    keywords: [
      "rollback",
      "roll",
      "back",
      "revert",
      "incident",
      "runbook",
      "champion",
      "previous",
      "reload",
      "recovery",
      "release",
    ],
    text: "Rollback in my lab moves the @champion alias back to the most recent approved version, tags the withdrawn version rolled_back with a reason, and writes an audit record; the promotion policy then refuses that version. In the drill on the Docker Compose stack, the API reloaded from v1 to v2, smoke tests asserted v2, rollback returned @champion to v1, and smoke tests asserted v1 again. The Kubernetes version is a Service selector switch between blue and green slots, verified against an API server but not with running pods. This was a drill, not a real production incident.",
  },
  {
    id: "responsible-ai",
    title: "Responsible AI evaluation",
    source: "ML Systems · Responsible AI",
    keywords: [
      "responsible",
      "fairness",
      "fair",
      "bias",
      "fairlearn",
      "shap",
      "explainability",
      "explanations",
      "subgroup",
      "model",
      "card",
      "ethics",
      "compliance",
      "regulatory",
      "rai",
      "equalized",
      "odds",
    ],
    text: "My Responsible AI evaluation runs on any registered model version in the lab: permutation SHAP (additivity error 2.3e-15), Fairlearn subgroup metrics for sex, race, age band, and native-country group with 300-resample bootstrap intervals, a minimum-size rule that kept 9 small groups out of comparisons, threshold sweeps, and Evidently with and without labels. For v1, women were selected 12.3% of the time vs 40.6% for men (equalized-odds difference 0.167), and a controlled shift raised that difference to 0.301. These are diagnostics only: I do not claim either model is fair, nothing here demonstrates regulatory compliance, and the release record always says the model is not approved for decisions about people.",
  },
  {
    id: "pytorch-tensorflow",
    title: "PyTorch and TensorFlow experience",
    source: "ML Systems · Training Benchmark",
    keywords: [
      "pytorch",
      "torch",
      "tensorflow",
      "keras",
      "tf",
      "deep",
      "learning",
      "framework",
      "frameworks",
      "training",
      "dataloader",
      "autograd",
      "checkpoint",
      "gradient",
      "accumulation",
    ],
    text: "I've used PyTorch in two personal projects: an MLP exported to ONNX in my MLOps lab, and a training benchmark where I rebuilt my from-scratch NumPy network in PyTorch and TensorFlow/Keras on identical data, weights, and batch order. In float64 the three agree to within 1e-15. The PyTorch trainer has a configurable DataLoader, gradient accumulation that exactly matches the larger batch, and checkpoints whose resume is bitwise identical. All of it ran on CPU; it is project experience, not framework work at an employer.",
  },
  {
    id: "cuda-mixed-precision",
    title: "CUDA, GPUs, and mixed precision",
    source: "ML Systems · Training Benchmark",
    keywords: [
      "cuda",
      "gpu",
      "gpus",
      "nvidia",
      "mixed",
      "precision",
      "amp",
      "fp16",
      "bf16",
      "bfloat16",
      "autocast",
      "gradscaler",
      "hardware",
      "accelerator",
      "a100",
      "h100",
    ],
    text: "Honest answer: I have not trained on GPUs. My benchmark ran on a 2-vCPU machine with no GPU. The mixed precision I actually executed is CPU bfloat16 autocast (the CPU supports AVX512_BF16 and AMX_BF16), which trained to the essentially the same accuracy as fp32 (90.27% vs 90.23% on digits) but ran slower at this tiny model size. The CUDA path (fp16 autocast with GradScaler) is implemented and tested to refuse to run without CUDA, but it has never executed, so I have no GPU numbers.",
  },
  {
    id: "distributed-training",
    title: "Distributed training and its limits",
    source: "ML Systems · Training Benchmark",
    keywords: [
      "distributed",
      "ddp",
      "data",
      "parallel",
      "multi-gpu",
      "multigpu",
      "nccl",
      "gloo",
      "mirroredstrategy",
      "mirrored",
      "strategy",
      "scaling",
      "cluster",
      "nodes",
      "horovod",
    ],
    text: "I ran PyTorch DistributedDataParallel as two CPU processes with the gloo backend, and TensorFlow MirroredStrategy on two logical CPU devices. Both match single-process training to within 5e-16 in float64, which shows the gradient synchronization is correct. Both were slower than one process (DDP 12.9 s per rank vs 3.4 s), because a tiny model on 2 vCPUs spends its time communicating. The launcher would pick NCCL with 2 or more GPUs, but I have never run multi-GPU or multi-node training, so I make no scaling claims.",
  },
  {
    id: "onnx-inference",
    title: "ONNX export and ONNX Runtime inference",
    source: "ML Systems · Training Benchmark",
    keywords: [
      "onnx",
      "onnxruntime",
      "runtime",
      "export",
      "inference",
      "latency",
      "serving",
      "optimization",
      "portable",
      "benchmark",
    ],
    text: "I export PyTorch models to ONNX in two projects. In the MLOps lab the PyTorch MLP is served through ONNX Runtime (max probability difference vs PyTorch 6.5e-8), which keeps PyTorch out of the serving image. In the training benchmark the exported model matched PyTorch within 1.0e-6 with 100% argmax agreement, and ONNX Runtime cut single-record p50 latency to 15 microseconds vs 32 for PyTorch eager on digits. Batches of 1,000 reached about 1.48 million rows per second on CPU.",
  },
  {
    id: "measured-results",
    title: "Measured results across my ML projects",
    source: "ML Systems · Results",
    keywords: [
      "results",
      "metrics",
      "numbers",
      "measured",
      "benchmark",
      "benchmarks",
      "accuracy",
      "auc",
      "performance",
      "outcomes",
      "impact",
      "tests",
    ],
    text: "All measured locally: MLOps lab test ROC AUC 0.913 (scikit-learn) and 0.919 (PyTorch via ONNX); micro-batching 1.95x throughput at 64 users; drift alert fired on shifted data (prediction drift 0.362); 93 automated tests. Responsible AI: 7 of 7 release checks for both model versions; SHAP additivity error 2.3e-15. Training benchmark: 90.2% digit and 90.9% face test accuracy over 3 seeds; NumPy, PyTorch, and Keras agree within 1e-15; bitwise-identical checkpoint resume. LLM FactCheck: normalized exact match 0.66 (direct) vs 0.69 (RAG). Every number comes from a results file or verification log in the project's repository.",
  },
  {
    id: "project-limitations",
    title: "Limitations of my ML projects",
    source: "ML Systems · Limitations",
    keywords: [
      "limitations",
      "limits",
      "weaknesses",
      "gaps",
      "missing",
      "caveats",
      "not",
      "verified",
      "honest",
      "honestly",
      "shortcomings",
      "lack",
    ],
    text: "The limits, plainly: everything ran on one 2-vCPU cloud VM with no GPU. No Kubernetes pod ran, Grafana was never rendered, and neither GitHub Actions workflow has run on GitHub yet. The load tests shared CPUs with the service, so they are relative. The census data is from 1994, the drift scenario is synthetic, and the fairness numbers are diagnostics, not a verdict. I have no GPU, multi-GPU, or production ML deployment experience to show from these projects.",
  },
  {
    id: "contributions",
    title: "My exact contributions",
    source: "ML Systems · Contributions",
    keywords: [
      "contribution",
      "contributions",
      "role",
      "did",
      "yourself",
      "own",
      "wrote",
      "author",
      "team",
      "solo",
      "alone",
      "responsible",
      "part",
      "ai-assisted",
      "claude",
      "coding",
      "assistant",
    ],
    text: "The MLOps lab, the Responsible AI evaluation, and the training benchmark are solo personal projects: I defined the scope and the evidence rules, and built them with AI coding assistance (Claude) as part of my workflow; every metric comes from a committed results file, and I can walk through any component. AgentMemry is my own library, published on PyPI. LLM FactCheck was a two-person study: I co-authored the paper and shared the manual error review, and the repository's code commits are my teammate's. None of these projects was done for TAIRC, KAVACH, or any other employer.",
  },

  // ---- Research ----
  {
    id: "research",
    title: "Research: LLM factual QA evaluation",
    source: "Research",
    keywords: [
      "research",
      "paper",
      "factcheck",
      "fact",
      "check",
      "evaluation",
      "bm25",
      "triviaqa",
      "hallucination",
      "publication",
      "co-author",
      "coauthor",
    ],
    text: "I co-authored LLM FactCheck with one teammate: an unpublished research study (written in a conference paper template, not published at any venue) benchmarking factual QA across direct LLM answering, BM25 retrieval, and BM25-grounded RAG on a controlled 100-question TriviaQA pilot. BM25 found supporting evidence for 90% of questions, yet going from direct answering to RAG raised normalized exact match only from 0.66 to 0.69 and token F1 from 0.784 to 0.803 (RAG fixed 10 answers but regressed 9), which points to evidence use and answer generation rather than retrieval as the bottleneck. We scored with exact match, token F1, a lexical groundedness proxy, and an unsupported-answer proxy, and the paper's eleven-category manual error review was done by both co-authors. The repository's commits are my teammate's. Repo: github.com/BaavanshReddy/LLM_factcheck.",
  },

  // ---- Portfolio ----
  {
    id: "portfolio",
    title: "This site: Chat-with-Baavansh",
    source: "Projects",
    keywords: [
      "site",
      "website",
      "portfolio",
      "this",
      "chat",
      "nextjs",
      "next",
      "built",
      "made",
      "assistant",
    ],
    text: "This site itself is a project: a Next.js portfolio with an assistant grounded in one structured knowledge base (lib/profile.ts and lib/caseStudies.ts). It is not a trained or fine-tuned model. With an API key configured, a server route sends the whole knowledge base to Claude as context and screens the reply against claim guardrails, falling back if a reply breaks them. Without a key, or if the API fails, a keyword-retrieval engine ranks knowledge chunks in the browser and answers with their text and sources.",
  },

  // ---- Leadership ----
  {
    id: "leadership",
    title: "Leadership & activities",
    source: "Leadership",
    keywords: [
      "leadership",
      "lead",
      "rupd",
      "police",
      "campus",
      "safety",
      "officer",
      "fraternity",
      "greek",
      "risk",
      "judiciary",
      "community",
      "service",
      "volunteer",
      "extracurricular",
      "activities",
      "enigma",
      "languages",
      "hindi",
      "telugu",
    ],
    text: "I served as a Community Service Officer with the Rutgers University Police Department (Jan 2025 – May 2026), supporting incident response and crowd management for large-scale university events. I held three elected positions in Alpha Phi Delta Fraternity (May 2024 – May 2026) as Risk Management Chair, Head of Judiciary Board, and Co-Brotherhood Chair, leading safety compliance, conduct governance, and member engagement. I was also Administration Secretary for ENIGMA Technical Society (Aug 2023 – May 2024), organizing technical workshops and streamlining communication. I speak English, Hindi, and Telugu.",
  },

  // ---- Pitch ----
  {
    id: "why-hire",
    title: "Why hire me",
    source: "Pitch",
    keywords: [
      "why",
      "hire",
      "fit",
      "best",
      "good",
      "reason",
      "value",
      "strong",
      "candidate",
      "recruit",
      "offer",
      "great",
      "pick",
      "choose",
    ],
    text: "Hire me if you want an engineer with four years of range already behind him. I've built production REST APIs and data pipelines, integrated LLM and ML components into backend services, spent two years on an IoT platform wiring device telemetry and AI detections into alert workflows, built business systems in Java and Spring Boot, and published an open-source memory library for AI agents on PyPI. On my own time I've built ML systems end to end and measured them honestly: a feature store, model registry, micro-batched serving, drift monitoring, and a Responsible AI evaluation. Underneath that I have rare systems depth (a compiler, a RISC-V CPU, and a Unix filesystem written from scratch), so I debug across the stack rather than at one layer. I test what I build and I take problems end to end.",
  },
  {
    id: "looking-for",
    title: "What I'm looking for",
    source: "Profile",
    keywords: [
      "looking",
      "want",
      "seeking",
      "roles",
      "role",
      "opportunity",
      "opportunities",
      "interested",
      "available",
      "open",
      "job",
      "hiring",
      "position",
      "type",
      "relocate",
      "sponsorship",
    ],
    text: "I'm open to backend engineering, AI/ML engineering, Python development, IoT and connected-systems engineering, and IT/infrastructure roles. I'm most excited by teams shipping real products to real users. My experience maps across all of those families: production backend and REST APIs, LLM and retrieval pipelines, two years of IoT platform work, low-level C systems, and cloud deployments, so I'm not locked into one narrow lane. I'm based in New Brunswick, NJ.",
  },

  // ---- Contact ----
  {
    id: "contact",
    title: "How to contact me",
    source: "Contact",
    keywords: [
      "contact",
      "email",
      "reach",
      "connect",
      "linkedin",
      "github",
      "resume",
      "résumé",
      "cv",
      "touch",
      "message",
      "available",
      "phone",
    ],
    text: "The fastest way to reach me is email: baavanshreddy@gmail.com. My GitHub (github.com/BaavanshReddy) and LinkedIn are linked in the navigation and the contact section of this site, and you can download my résumé there too.",
  },

  // ---- Education ----
  {
    id: "education",
    title: "Education",
    source: "Education",
    keywords: [
      "education",
      "school",
      "college",
      "university",
      "rutgers",
      "degree",
      "study",
      "studied",
      "studying",
      "classes",
      "class",
      "student",
      "major",
      "graduate",
      "gpa",
      "coursework",
      "magna",
      "cum",
      "laude",
      "deans",
      "list",
      "honors",
    ],
    text: "I graduated from Rutgers University, New Brunswick in May 2026 with a B.S. in Computer Science, Magna Cum Laude, with a 3.76 GPA and four semesters on the Dean's List (Fall '24, Spring '25, Fall '25, Spring '26). My relevant coursework: Data Structures & Algorithms, Computer Architecture, Operating Systems, Compilers, Software Engineering, Databases, and Artificial Intelligence.",
  },
];
